import type { Client, Bot, AuditProcedure, AuditData } from '@/types/index.types';

const Clients: Client[] = [
  {
    client_id: 'C-1001',
    name: 'Tata Motors',
    industry: 'Automobile',
    timestamp: new Date(),
    audit_procedures: 14,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1002',
    name: 'Tech Innovators',
    industry: 'Technology',
    timestamp: new Date(),
    audit_procedures: 25,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1003',
    name: 'Global Foods',
    industry: 'Manufacturing',
    timestamp: new Date(),
    audit_procedures: 10,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1004',
    name: 'EcoBuild',
    industry: 'Manufacturing',
    timestamp: new Date(),
    audit_procedures: 16,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1005',
    name: 'Finserve Solutions',
    industry: 'Technology',
    timestamp: new Date(),
    audit_procedures: 20,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1006',
    name: 'Greenwave Energy',
    industry: 'Energy',
    timestamp: new Date(),
    audit_procedures: 8,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1007',
    name: 'Apex Pharmaceuticals',
    industry: 'Healthcare',
    timestamp: new Date(),
    audit_procedures: 18,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1008',
    name: 'Urban Retail Co.',
    industry: 'Retail',
    timestamp: new Date(),
    audit_procedures: 12,
    action: ['share', 'delete'],
  },
  {
    client_id: 'C-1009',
    name: 'Orbit Logistics',
    industry: 'Transportation',
    timestamp: new Date(),
    audit_procedures: 22,
    action: ['share', 'delete'],
  },
];

const bots: Bot[] = [
  {
    id: "p2p",
    category: "P2P",
    auditProcedure: "Prevent duplicate vendors",
    description: "Detects and prevents creation of duplicate vendor records in the system.",
    documentForEvidence: "PAN Certificate",
    company: "Capital India Private Limited",
    location: "Mumbai",
    period: "Quarterly",
    fYear: "2024-25",
    industry: "Manufacturing",
  },
  {
    id: "h2r",
    category: "H2R",
    auditProcedure: "Ghost employee detection",
    description: "Compares payroll records with attendance data to detect non-existent employees drawing salaries.",
    documentForEvidence: "Employee Master Report",
    company: "Tata Motors",
    location: "Pune",
    period: "Q1",
    fYear: "2024-25",
    industry: "Automobile",
  },
  {
    id: "p2p-match",
    category: "P2P",
    auditProcedure: "Ensure PO-GRN-Invoice match",
    description: "Performs automated 3-way matching between Purchase Orders, GRNs, and Invoices to ensure accuracy before payment.",
    documentForEvidence: "PO, GRN & Invoice Copies",
    company: "Reliance Industries",
    location: "Mumbai",
    period: "Q2",
    fYear: "2024-25",
    industry: "Energy",
  },
  {
    id: "h2r-salary",
    category: "H2R",
    auditProcedure: "Identify salary outliers",
    description: "Monitors employee salary trends and flags anomalies or inconsistent salary increments for review.",
    documentForEvidence: "Salary Benchmarking Sheet",
    company: "Wipro",
    location: "Bengaluru",
    period: "Monthly",
    fYear: "2024-25",
    industry: "IT Services",
  },
  {
    id: "otr-travel",
    category: "OTR",
    auditProcedure: "Travel expense fraud detection",
    description: "Validates travel claims against booking data and location tracking to spot fraudulent claims.",
    documentForEvidence: "Travel Expense Report",
    company: "Hindustan Unilever",
    location: "Kolkata",
    period: "Half-Yearly",
    fYear: "2023-24",
    industry: "FMCG",
  },
  {
    id: "f2f-collection",
    category: "F2F",
    auditProcedure: "Monitor receivable aging",
    description: "Analyzes customer outstanding balances and flags overdue receivables.",
    documentForEvidence: "AR Aging Report",
    company: "Tata Motors",
    location: "Chennai",
    period: "Q3",
    fYear: "2023-24",
    industry: "Automobile",
  },
  {
    id: "it-access",
    category: "ITGC",
    auditProcedure: "Periodic user access review",
    description: "Automates user access review to ensure only authorized individuals retain system access.",
    documentForEvidence: "Access Logs",
    company: "Capital India Private Limited",
    location: "Noida",
    period: "Quarterly",
    fYear: "2024-25",
    industry: "Cybersecurity",
  },
  {
    id: "p2p-rate",
    category: "P2P",
    auditProcedure: "Rate contract deviation check",
    description: "Checks purchase orders against approved vendor rate contracts to identify price deviations.",
    documentForEvidence: "Rate Contract Agreement",
    company: "Mahindra & Mahindra",
    location: "Hyderabad",
    period: "Q4",
    fYear: "2024-25",
    industry: "Manufacturing",
  },
  {
    id: "h2r-overtime",
    category: "H2R",
    auditProcedure: "Overtime abuse monitoring",
    description: "Analyzes overtime patterns to detect excessive or unauthorized overtime payouts.",
    documentForEvidence: "Timesheet & Payroll Report",
    company: "Infosys",
    location: "Bengaluru",
    period: "Monthly",
    fYear: "2024-25",
    industry: "IT Services",
  },
  {
    id: "otr-fleet",
    category: "OTR",
    auditProcedure: "Fuel consumption analytics",
    description: "Monitors vehicle fuel consumption and flags anomalies against standard mileage benchmarks.",
    documentForEvidence: "Fuel Log Sheets",
    company: "LogiTrans Ltd",
    location: "Surat",
    period: "Quarterly",
    fYear: "2024-25",
    industry: "Logistics",
  },
  {
    id: "extra-1",
    category: "P2P",
    auditProcedure: "Detect post-invoice POs",
    description: "Flags purchase orders created after the corresponding invoice date.",
    documentForEvidence: "Invoice & PO copies",
    company: "Capitall India Pvt. Ltd.",
    location: "Ahmedabad",
    period: "Q1",
    fYear: "2024-25",
    industry: "Retail",
  },
];

const audit_Procedures: AuditProcedure[] = [
  {
    id: '1',
    category: 'P2P',
    name: 'Prevent duplicate vendors',
    description: 'Detects and prevents creation of duplicate...',
    document: 'PAN certificate',
  },
  {
    id: '2',
    category: 'H2R',
    name: 'Ghost employee detection',
    description: 'Compares payroll records with attendance...',
    document: 'Invoice',
  },
  {
    id: '3',
    category: 'P2P',
    name: 'Ensure PO–GRN–Invoice match',
    description: 'Performs automated 3-way matching bet...',
    document: 'Invoice',
  },
  {
    id: '4',
    category: 'H2R',
    name: 'Unauthorized salary changes',
    description: 'Monitors and logs modifications in payroll...',
    document: 'Quotations',
  },
  {
    id: '5',
    category: 'P2P',
    name: 'Detect post-invoice POs',
    description: 'Flags purchase orders created after the c...',
    document: 'GST Certificate',
  },
];


export const auditData: AuditData[] = [
  {
    jobId: "10102025-001",
    location: "Mumbai",
    auditProcedures: 112,
    exceptions: 167,
    startDate: "2024-04-23",
    endDate: "2025-01-03",
    createdOn: "2024-04-23",
    status: "In-Progress",
  },
  {
    jobId: "20240315-004",
    location: "Bengaluru",
    auditProcedures: 187,
    exceptions: 213,
    startDate: "2024-05-16",
    endDate: "2025-02-14",
    createdOn: "2024-05-16",
    status: "Completed",
  },
  {
    jobId: "20240315-008",
    location: "Chennai",
    auditProcedures: 145,
    exceptions: 154,
    startDate: "2024-06-28",
    endDate: "2025-03-29",
    createdOn: "2024-06-28",
    status: "Inactive",
  },
  {
    jobId: "20240315-007",
    location: "Kolkata",
    auditProcedures: 163,
    exceptions: 189,
    startDate: "2024-07-04",
    endDate: "2025-04-17",
    createdOn: "2024-07-04",
    status: "Completed",
  },
  {
    jobId: "20240315-006",
    location: "Hyderabad",
    auditProcedures: 152,
    exceptions: 172,
    startDate: "2024-08-19",
    endDate: "2025-05-22",
    createdOn: "2024-08-19",
    status: "Inactive",
  },
  {
    jobId: "20240315-003",
    location: "Pune",
    auditProcedures: 198,
    exceptions: 234,
    startDate: "2024-09-22",
    endDate: "2025-06-03",
    createdOn: "2024-09-22",
    status: "Inactive",
  },
  {
    jobId: "20240315-002",
    location: "Ahmedabad",
    auditProcedures: 105,
    exceptions: 87,
    startDate: "2024-10-01",
    endDate: "2025-07-18",
    createdOn: "2024-10-01",
    status: "Inactive",
  },
  {
    jobId: "20240315-008",
    location: "Surat",
    auditProcedures: 176,
    exceptions: 195,
    startDate: "2024-11-15",
    endDate: "2025-08-26",
    createdOn: "2024-11-15",
    status: "Completed",
  },
]

export {bots, Clients, audit_Procedures};